azure_endpoint:
  scoring_uri: http://d425a0dd-ef72-4bea-b2d2-bff2d2fce7e5.eastasia.azurecontainer.io/score
azure_workspace_config:
  resource_group: mlflow_azure
  subscription_id:
  workspace_location: East US
  workspace_name: MLOps-Azure
model_config:
  aci_service_name: sklearn-model-dev5
  description: sklearn model
  image_name: sklearnimage
  model_name: sklearn_dev_model1
  model_uri: runs:/bee643b6044e45a8968bae8462e4b23a/model
